# Site
repository: sasanasadiabadi.github.io/cv
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Sasan Asadiabadi, Ph.D.
title: AI Research Engineer 
email: sabadi15@ku.edu.tr
# email_title: Email (Email title override)
#phone: +31 625598532
# phone_title: Phone (Phone title override)
website: sasanasadiabadi.github.io
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: jekyllrb
github_username:  sasanasadiabadi
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
instagram_username: sasaan.asadi
linkedin_username: sasan-asadiabadi-1211678a
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#orcid_username: 0000-0000-0000-0000
googlescholar_username: citations?user=Z27B5dYAAAAJ&hl=en

# Additional icon links
additional_links:
#- title: Link name
#  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/me.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a computer vision and deep learning enginner, enthusiastic about vastly growing industrial applications of AI. 
  I'm passionate about solving real world problems with a strong research background in industry and academy. Having experienced working with people from around the world
  in various teams and under different industry systems.

  My work and research focuses on **spatio-temporal medical image analysis, multimodal signal processing, light-weight neural networks and deep learning on edge**. I'm mostly intrested in designing and optimizing 
  deep neural networks for real-time intelligent data-driven systems. 
content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: rtMRI-VTAT
        link: https://github.com/sasanasadiabadi/rtMRI-VTAT
        link_text: https://github.com/sasanasadiabadi/rtMRI-VTAT
        additional_links:
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: https://github.com/sasanasadiabadi/rtMRI-VTAT
          #- title:  Github page for project (eg. sproogen/modern-resume-theme)
          #  icon: fab fa-github
          #  url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          rtMRI-VTAT is a Python-based GUI and a vocal tract analysis tool for rtMRI datasets.
        description: | # this will include new lines to allow paragraphs
          My Ph.D research was centered around localizing anatomical landmarks of the vocal tract in real-time MRI videos and analysing how speech articulators change over time as we utter a sentence.
          VTAT is a GUI-based vocal tract analysis tool, which aims to help the researchers to track vocal tract contours in MRI videos and study the fundementals of human speech production. VTAT is 
          based on a **light-weight MobileNet-V3 backbone** and a **UNet architecutre**, which estimates the vocal tract landmarks via heatmap regression.
  - title: Experience
    layout: list
    content:
      - layout: left
        border: weak 
        title: ScreenPoint Medical, The Netherlands
        sub_title: AI Research Engineer
        caption: May 2022 - present
        link: https://screenpoint-medical.com/
        quote: >
          Smart AI for early breast cancer detection and diagnosis.
        description: | # this will include new lines to allow paragraphs
          Research and development of Transpara, an AI based system for early detection of breast cancer in 2D and 3D mammograms, aimed at improving performance to the level of expert radiologists and beyond.
      - layout: left
        border: weak 
        title: Wageningen University & Research, The Netherlands
        sub_title: Postdoctoral Researcher
        caption: Feb 2021 - Apr 2022
        link: https://www.wur.nl/en.htm
        quote: >
          Conducting research project  under the [4TU Precision Medicine](https://www.4tu.nl/precision-medicine/).
        description: | # this will include new lines to allow paragraphs
          I conduct my postdoctoral research as a member of Laboratory of Biophysics [BIP](https://www.wur.nl/en/Research-Results/Chair-groups/Agrotechnology-and-Food-Sciences/Laboratory-of-Biophysics.htm) at WUR.
          My research mainly focuses on applications of deep learning in analysis of quantitative MRI. I implement neural networks for spatio-temporal modeling of 3D MRI data and unsupervised clustering of biological tissues.
      - layout: left
        border: weak 
        title: RaSpect Intelligence Inspection Limited, Hong  Kong
        sub_title: Senior AI Research Engineer
        caption: May 2018 - Feb 2021
        link: https://raspect.ai/en
        quote: >
          Responsible for development of intelligent inspection systems for safer cities.
        description: | # this will include new lines to allow paragraphs
          RaSpect is a drone-based intelligent inspection company and over there I did research and development of deep learning algorithms centered around the  facade element and defect detection.
          We utilized drones to capture images/videos of facades and  developed deep models to localize the deffective areas in the orthophoto stiched images. Check our patent at 
          [Systems and methods for artificial intelligence powered inspections and predictive analyses](https://patents.google.com/patent/WO2021224893A1)
      - layout: left
        border: weak 
        title: CY Vision, Turkey
        sub_title: Computer Vision Engineer
        caption: Jul 2019 - Jan 2021
        link: https://www.cyvision.com/
        quote: >
          Responsible for development of real-time driver monitoring system.
        description: | # this will include new lines to allow paragraphs
          In my role as a computer vision engineer at CY Vision, I did extensive research on deep learning on edge. I developed efficient light-weight neural networks for tracking driver's facial landmarks and pupils 
          from a stero-vision camera behind the steering wheel, robust to occlusion and different lighting conditions. I worked on optimizing and deploying the deep learning models
          on edge devices like low power ARM processors with C++. 
      - layout: left
        border: weak 
        title: Eyris Technologies, California
        sub_title: Deep Learning Engineer
        caption: Jan 2020 - Feb 2021
        link: https://www.eyeris.ai/
        quote: >
          In-cabin driver 3D gaze and pose estimation system using monocular vision.
        description: | # this will include new lines to allow paragraphs
          At Eyeris I developed a real-time 3D gaze and pose estimation system for tracking driver's behavior in the video stream being captured from the central mirror.
      - layout: left
        border: weak 
        title: Koç University, Turkey
        sub_title: Research Assistant
        caption: Feb 2015 - Feb 2020
       # link: Link to company (optional)
        quote: >
          I conducted research in the topic of applications of computer vision and deep learning in medical image analysis.
        description: | # this will include new lines to allow paragraphs
          During my M.Sc. and Ph.D. career, I have mainly focused on analyzing medical images using various deep learning and computer vision techniques. I have worked on several
          projects including localizing anatomical landmarks on human vocal tract in real time MRI sequences, biomedical image segmentation, blind estimation of vocal tract articulatory features from speech 
          and generating visual face animations synchronized with input speech. 
      - layout: left
        border: weak 
        title: Koç University, Turkey
        sub_title: Instructor
        caption: Feb 2020 - Jun 2020
       # link: Link to company (optional)
        quote: >
          Teaching a Python programming language cource.
        description: | # this will include new lines to allow paragraphs
          In my academic career, I have gained teaching experience by fulfilling my teaching assistance duties for several undergraduate and graduate courses.
          As well, I have lectured a course “introductionto programming with Python” to undergraduate students with non engineering backgrounds.
  - title: Education
    layout: list
    content:
      - layout: left
        border: weak 
        title: Koç University, Turkey
        sub_title: Ph.D.in Electrical Engineering
        caption: Jan 2017 - Jan 2021
        quote: >
          Under supervision of Prof. Engin Erzin.
        description: | # this will include new lines to allow paragraphs
          Thesis title: Deep Learning Approaches for Vocal Tract Boundary Segmentation in rtMRI,
      - layout: left
        border: weak 
        title: Koç University, Turkey
        sub_title: M.Sc. in Electrical Engineering
        caption: Feb 2015 - Jan 2017
        quote: >
          Under supervision of Prof. Engin Erzin.
        description: | # this will include new lines to allow paragraphs
          Thesis title: Vocal Tract Contour Tracking for real-time Speech MRI Using a Shape Model Prior.
      - layout: left
        border: weak 
        title: Sharif University of Technology, Iran
        sub_title: B.Sc. in Electrical Engineering
        caption: Sep 2009 - Dec 2014
        quote: >
          Under supervision of Dr. Gholampour.
        description: | # this will include new lines to allow paragraphs
          Project title: Voice Activity Detection for Squelch Systems in Noisy Environment.
  - title: Skills # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Machine Learning  
        description: | # this will include new lines to allow paragraphs
          Deep Learning, Supervised Learning, Unsupervised Learning, Representation Learning
      - layout: left
        title: Expertise  
        description: | # this will include new lines to allow paragraphs
          Medical Image Segmentation, Facial Landmark Localization, Object Detection, Facial Animation Synthesis
      - layout: left
        title: Software  
        description: | # this will include new lines to allow paragraphs
          - Programming Languages: Python, C++
          -	Deep Learning Frameworks: Pytorch, TensorFlow, Keras 
          - Inference on Edge: TensorRT, MNN, OpenCV DNN, ONNXRuntime 
          - Computer Vision: OpenCV (Python, C++), Scikit-image
          -	Data Analytics and Visualization Modules: Numpy, Pandas, Scipy, Scikit-learn, Matplotlib, Seaborn
          - Versioning tools: Git
  - title: Publications
    layout: text
    content: | # this will include new lines to allow paragraphs
      - **S. Asadiabadi**, E Erzin, Vocal Tract Contour Tracking in rtMRI Using Deep Temporal Regression Network, IEEE/ACM Transactions on Audio Speech and Language Processing, 2020.
      - **S. Asadiabadi**, E. Erzin, Automatic Vocal Tract Landmark Tracking In RT-MRI Using Fully Convilutional Networks and Kalman Filter, IEEE Conference on ICASSP, 2020,Barcelona, Spain.
      - R. Sadiq, **S. Asadiabadi**, E. Erzin, Emotion Dependent Facial Animation from Affective Speech, IEEE Workshop on MMSP, 2020, Tampere, Finland.
      - M. De Filippo, **S. Asadiabadi**, N. Ko, H. Sun, Concept of a Computer-Vision-Based Algorithm for Detecting Thermal Anomalies in Reinforced Concrete
      Structures, Multidisciplinary Digital Publishing Institute Proceedings, 2019, Florence, Italy.
      - **S. Asadiabadi**, E. Erzin, A Deep Learning Approach for Data Driven Vocal Tract Area Function Estimation, IEEE Workshop on Spoken Language Technology, 2018, Athens, Greece.
      - **S. Asadiabadi**, R. Sadiq, E. Erzin, Multimodal Speech Driven Facial Animation Using Deep Neural Networks, APSIPA ASC, 2018, Honolulu, Hawaii.
      - **S. Asadiabadi**, E. Erzin, Vocal Tract Airway Tissue Boundary Tracking for rtMRI using Shape and Appearance Priors, In Proceedings of INTERSPEECH, 2017, Stockholm, Sweden.

  
  - title: Languages
    layout: text
    content: | # this will include new lines to allow paragraphs
      English (Fluent), Turkish (Fluent), Persian (Native)
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Non-smoker. Interested in sports, hiking, board games and traveling.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
